#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_ENEMY_EXTENSION 15
#define ID_TEX_MISC 20
#define ID_TEX_TILES 40
#define ID_TEX_MISC_EXTENSION 60
#define ID_TEX_ENEMY_KOOPA 50


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_DECORATION 6
#define OBJECT_TYPE_BLOCK 7
#define OBJECT_TYPE_PIPE 8
#define OBJECT_TYPE_FIRE_PIRANHA 9
#define OBJECT_TYPE_INVISIBLE_BLOCK 10

#define OBJECT_TYPE_PORTAL	50

#define OBJECT_TYPE_LUCKYBLOCK -1
#define OBJECT_TYPE_RED_GOOMBA	-2
#define OBJECT_TYPE_GOAL_ROULETTE_ICON	-3

#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_BRICK 20000


#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

#define ID_SPIRTE_GROUND 60000
#define ID_SPRITE_GROUND_1 (ID_SPIRTE_GROUND + 1000)
#define ID_SPRITE_GROUND_2 (ID_SPIRTE_GROUND + 2000)
#define ID_SPRITE_GROUND_3 (ID_SPIRTE_GROUND + 3000)
#define ID_SPRITE_GROUND_4 (ID_SPIRTE_GROUND + 4000)
#define ID_SPRITE_GROUND_5 (ID_SPIRTE_GROUND + 5000)
#define ID_SPRITE_GROUND_6 (ID_SPIRTE_GROUND + 6000)

#define ID_SPRITE_BUSH 70000
#define ID_SPRITE_BUSH_1 (ID_SPRITE_BUSH + 1000)
#define ID_SPRITE_BUSH_2 (ID_SPRITE_BUSH + 2000)
#define ID_SPRITE_BUSH_3 (ID_SPRITE_BUSH + 3000)
#define ID_SPRITE_BUSH_4 (ID_SPRITE_BUSH + 4000)
#define ID_SPRITE_BUSH_5 (ID_SPRITE_BUSH + 5000)
#define ID_SPRITE_BUSH_6 (ID_SPRITE_BUSH + 6000)
#define ID_SPRITE_BUSH_7 (ID_SPRITE_BUSH + 7000)
#define ID_SPRITE_BUSH_8 (ID_SPRITE_BUSH + 8000)

#define ID_SPRITE_ORANGE_BLOCK 80000
#define ID_SPRITE_ORANGE_BLOCK_1 (ID_SPRITE_ORANGE_BLOCK + 1000)
#define ID_SPRITE_ORANGE_BLOCK_2 (ID_SPRITE_ORANGE_BLOCK + 2000)
#define ID_SPRITE_ORANGE_BLOCK_3 (ID_SPRITE_ORANGE_BLOCK + 3000)
#define ID_SPRITE_ORANGE_BLOCK_4 (ID_SPRITE_ORANGE_BLOCK + 4000)
#define ID_SPRITE_ORANGE_BLOCK_5 (ID_SPRITE_ORANGE_BLOCK + 5000)
#define ID_SPRITE_ORANGE_BLOCK_6 (ID_SPRITE_ORANGE_BLOCK + 6000)
#define ID_SPRITE_ORANGE_BLOCK_7 (ID_SPRITE_ORANGE_BLOCK + 7000)
#define ID_SPRITE_ORANGE_BLOCK_8 (ID_SPRITE_ORANGE_BLOCK + 8000)
#define ID_SPRITE_ORANGE_BLOCK_9 (ID_SPRITE_ORANGE_BLOCK + 9000)

#define ID_SPRITE_BLUE_BLOCK 90000	
#define ID_SPRITE_BLUE_BLOCK_1 (ID_SPRITE_BLUE_BLOCK + 1000)
#define ID_SPRITE_BLUE_BLOCK_2 (ID_SPRITE_BLUE_BLOCK + 2000)
#define ID_SPRITE_BLUE_BLOCK_3 (ID_SPRITE_BLUE_BLOCK + 3000)
#define ID_SPRITE_BLUE_BLOCK_4 (ID_SPRITE_BLUE_BLOCK + 4000)
#define ID_SPRITE_BLUE_BLOCK_5 (ID_SPRITE_BLUE_BLOCK + 5000)
#define ID_SPRITE_BLUE_BLOCK_6 (ID_SPRITE_BLUE_BLOCK + 6000)
#define ID_SPRITE_BLUE_BLOCK_7 (ID_SPRITE_BLUE_BLOCK + 7000)
#define ID_SPRITE_BLUE_BLOCK_8 (ID_SPRITE_BLUE_BLOCK + 8000)
#define ID_SPRITE_BLUE_BLOCK_9 (ID_SPRITE_BLUE_BLOCK + 9000)

#define ID_SPRITE_GREEN_BLOCK 140000
#define ID_SPRITE_GREEN_BLOCK_1 (ID_SPRITE_GREEN_BLOCK + 1000)
#define ID_SPRITE_GREEN_BLOCK_2 (ID_SPRITE_GREEN_BLOCK + 2000)
#define ID_SPRITE_GREEN_BLOCK_3 (ID_SPRITE_GREEN_BLOCK + 3000)
#define ID_SPRITE_GREEN_BLOCK_4 (ID_SPRITE_GREEN_BLOCK + 4000)
#define ID_SPRITE_GREEN_BLOCK_5 (ID_SPRITE_GREEN_BLOCK + 5000)
#define ID_SPRITE_GREEN_BLOCK_6 (ID_SPRITE_GREEN_BLOCK + 6000)
#define ID_SPRITE_GREEN_BLOCK_7 (ID_SPRITE_GREEN_BLOCK + 7000)
#define ID_SPRITE_GREEN_BLOCK_8 (ID_SPRITE_GREEN_BLOCK + 8000)
#define ID_SPRITE_GREEN_BLOCK_9 (ID_SPRITE_GREEN_BLOCK + 9000)

#define ID_SPIRTE_WHITE_BLOCK 150000
#define ID_SPRITE_WHITE_BLOCK_1 (ID_SPIRTE_WHITE_BLOCK + 1000)
#define ID_SPRITE_WHITE_BLOCK_2 (ID_SPIRTE_WHITE_BLOCK + 2000)
#define ID_SPRITE_WHITE_BLOCK_3 (ID_SPIRTE_WHITE_BLOCK + 3000)
#define ID_SPRITE_WHITE_BLOCK_4 (ID_SPIRTE_WHITE_BLOCK + 4000)
#define ID_SPRITE_WHITE_BLOCK_5 (ID_SPIRTE_WHITE_BLOCK + 5000)
#define ID_SPRITE_WHITE_BLOCK_6 (ID_SPIRTE_WHITE_BLOCK + 6000)
#define ID_SPRITE_WHITE_BLOCK_7 (ID_SPIRTE_WHITE_BLOCK + 7000)
#define ID_SPRITE_WHITE_BLOCK_8 (ID_SPIRTE_WHITE_BLOCK + 8000)
#define ID_SPRITE_WHITE_BLOCK_9 (ID_SPIRTE_WHITE_BLOCK + 9000)

#define ID_SPRITE_BLOCK_SHADOW 100000
#define ID_SPRITE_BLOCK_SHADOW_1 (ID_SPRITE_BLOCK_SHADOW + 1000)
#define ID_SPRITE_BLOCK_SHADOW_2 (ID_SPRITE_BLOCK_SHADOW + 2000)
#define ID_SPRITE_BLOCK_SHADOW_3 (ID_SPRITE_BLOCK_SHADOW + 3000)
#define ID_SPRITE_BLOCK_SHADOW_4 (ID_SPRITE_BLOCK_SHADOW + 4000)
#define ID_SPRITE_BLOCK_SHADOW_5 (ID_SPRITE_BLOCK_SHADOW + 5000)

#define ID_SPRITE_PIPE 110000
#define ID_SPRITE_PIPE_1 (ID_SPRITE_PIPE + 1000)
#define ID_SPRITE_PIPE_2 (ID_SPRITE_PIPE + 2000)
#define ID_SPRITE_PIPE_3 (ID_SPRITE_PIPE + 3000)
#define ID_SPRITE_PIPE_4 (ID_SPRITE_PIPE + 4000)

#define ID_SPRITE_PIRANHA 120000
#define ID_SPRITE_PIRANHA_FIRE_UP_LEFT (ID_SPRITE_PIRANHA + 1000)
#define ID_SPRITE_PIRANHA_FIRE_UP_RIGHT (ID_SPRITE_PIRANHA + 2000)
#define ID_SPRITE_PIRANHA_FIRE_DOWN_LEFT (ID_SPRITE_PIRANHA + 3000)
#define ID_SPRITE_PIRANHA_FIRE_DOWN_RIGHT (ID_SPRITE_PIRANHA + 4000)

#define ID_SPITE_FIRE_BULLET 130000
#define ID_SPITE_FIRE_BULLET_1 (ID_SPITE_FIRE_BULLET + 1000)
#define ID_SPITE_FIRE_BULLET_2 (ID_SPITE_FIRE_BULLET + 2000)
#define ID_SPITE_FIRE_BULLET_3 (ID_SPITE_FIRE_BULLET + 3000)
#define ID_SPITE_FIRE_BULLET_4 (ID_SPITE_FIRE_BULLET + 4000)


#define ID_SPIRTE_CLOUD_NEW 160000
#define ID_SPIRTE_CLOUD_NEW_1 (ID_SPIRTE_CLOUD_NEW + 1000)
#define ID_SPIRTE_CLOUD_NEW_2 (ID_SPIRTE_CLOUD_NEW + 2000)

#define ID_SPITE_LUCKYBLOCK	-20000
#define ID_SPITE_LUCKYBLOCK_1 (ID_SPITE_LUCKYBLOCK -1)
#define ID_SPITE_LUCKYBLOCK_2 (ID_SPITE_LUCKYBLOCK -2)
#define ID_SPITE_LUCKYBLOCK_3 (ID_SPITE_LUCKYBLOCK -3)
#define ID_SPITE_LUCKYBLOCK_4 (ID_SPITE_LUCKYBLOCK -4)
#define ID_SPITE_LUCKYBLOCK_5 (ID_SPITE_LUCKYBLOCK -5)

#define ID_SPRITE_ENDING_SITE	-100003